//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlowForecastData
    {
        public int Id { get; set; }
        public int Date { get; set; }
        public string DateString { get; set; }
        public decimal Balance { get; set; }
        public int EntityId { get; set; }
    }
}
