//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthBuilder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public decimal Deposit { get; set; }
        public decimal Withdrawal { get; set; }
        public bool Cleared { get; set; }
        public string CheckNumber { get; set; }
        public bool Reconciled { get; set; }
        public string Notes { get; set; }
        public int AccountId { get; set; }
        public int TaxFormId { get; set; }
        public int TaxCategoryId { get; set; }
        public int CategoryId { get; set; }
        public int AssetId { get; set; }
        public int ContractorId { get; set; }
    }
}
